### ISSUE TITLE
Implement Zoomlevels

### ISSUE THREAD

**Issue by FreaKzero** [FreaKzero/ssgl-doom-launcher#20]

**Comment by FreaKzero** [comment]
@duganchen since i know that you have a development environment installed - can you test this stuff out on linux ?

Just check the "zoomlevels" branch out and use it via the dev environment (just have to setup stuff for the build yet)

with ? you can open a hotkey menu
with CTRL + PLUS you can increase the Zoomlevel
with CTRL + MINUS you can decrease the Zoomlevel

**Comment by duganchen** [comment]
Thanks! It works great.

**Comment by FreaKzero** [comment]
Thanks for testing - Will come most likely this weekend with v1.1.1
