### ISSUE TITLE
gnome crashes

### ISSUE THREAD

**Issue by whiper** [FreaKzero/ssgl-doom-launcher#25]
it happens when the program presents which game one would like to play with a selected wad. gnome is restarted automatically and comes back without desktop effects, and then the program works normally. in my configuration, only zandronum was set as a source-port. tested on debian jessie (stable) AMD64.

**Comment by FreaKzero** [comment]
This can happen because of: http://news.softpedia.com/news/gnome-shell-browser-plugin-crash-in-mozilla-firefox-patched-for-gnome-3-18-496391.shtml

SSGL is written in JavaScript and runs in an Application container named NWJS which uses Webkit.

**Comment by whiper** [comment]
we need someone else to confirm this also happens to them in another environment also. enlightenment 17 also crashes and comes back with an opengl error, so there is a chance that the video driver is the problem or even the hardware itself (VGA compatible controller: Intel Corporation Mobile GM965/GL960 Integrated Graphics Controller (primary) (rev 03)).

**Comment by FreaKzero** [comment]
So the workflow is like this ?

- Select List / Wads
 -Press SSGL Play button
- Crash

or:
- Select List / Wads
 -Press SSGL Play button
- Select iWAD from bottomlist
- Crash

**Comment by whiper** [comment]
the former.

> Select List / Wads
> Click SSGL Play button
> Crash

i am closing this until i get the chance to test on other hardware. i don't want to waste your time.
