### ISSUE TITLE
broadcast lan games

### ISSUE THREAD

**Issue by whiper** [FreaKzero/ssgl-doom-launcher#26]
currently, to setup lan games with zdoom or gzdoom, it is required that one knows the other users ip plus basic configuration like game mode (team, dm, coop, maybe there are others). this would greatly ease game setup.

this is a feature request rather than a bug.

**Comment by FreaKzero** [comment]
That feature is actually "longterm planned" also with an integrated chatlobby via websockets.
I have to refactor some things first because i want to update the NWJS Version.
