### ISSUE TITLE
Support for .pk7 format for mods

### ISSUE THREAD

**Issue by akrejczinger** [FreaKzero/ssgl-doom-launcher#38]

**Comment by FreaKzero** [comment]
never saw pk7 mods.
Also tried to find something with pk7 - maybe you can provide some url to a pk7 map/mod  ?

**Comment by HoborgHUN** [comment]
The Doom4 for Doom mod has a pk7 format: http://www.moddb.com/mods/d4d-doom4-for-doom
pk7 support might be sourceport-specific, I only tested this with gzdoom. If not using the launcher and manually dragging the mod file onto the exe, it works.

**Comment by FreaKzero** [comment]
ive added pk7 to the allowed files for the fileloader - but still the newest version of d4d is a pk3 ?

**Comment by FreaKzero** [comment]
Fixed with https://github.com/FreaKzero/ssgl-doom-launcher/commit/44149810338bcf078e917305d532564bd371f9db

**Comment by akrejczinger** [comment]
So I've found another mod. It's a zip file containing a bunch of pk7 files.
http://www.moddb.com/games/doom/addons/hxrtc-ultimate-pack
I tested the dev branch with this mod, and it seems like the files appear on the menu and I can select them, but they don't actually get loaded into the game.
Manually running them with drag-and-drop works. I hope you can test it with this link.

**Comment by FreaKzero** [comment]
Closing this due to: https://github.com/FreaKzero/ssgl-doom-launcher/blob/v1/README.md
