### ISSUE TITLE
launcher panics when trying to start gzdoom

### ISSUE THREAD

**Issue by nojusr** [FreaKzero/ssgl-doom-launcher#45]
whenever i try to launch gzdoom with this launcher i get this issue:
![2018-07-07-165918_1000x650_scrot](https://user-images.githubusercontent.com/24498517/42411585-2b9f25d8-8207-11e8-945a-1b7228af4fb7.png)

paniclog.txt:
No Engine to start given

TypeError: Cannot read property 'filter' of undefined

config.json:
{
    "active": {
        "doom64ex": false,
        "doomretro": false,
        "doomrpg": false,
        "doomrpgrl": false,
        "doomrpgrlmonsters": false,
        "gzdoom": true,
        "oblige": false,
        "prboomp": false,
        "zandronum": false,
        "zdoom": false
    },
    "dontShowUpdate": "0.0.0",
    "engines": {
        "doom64ex": "",
        "doomretro": "",
        "doomrpg": "",
        "doomrpgrl": "",
        "gzdoom": "/usr/bin/gzdoom",
        "prboomp": "",
        "zandronum": "",
        "zdoom": ""
    },
    "freshinstall": false,
    "initList": "false",
    "iwadpath": "/home/nojus/games/DOOM(original)/iwad/",
    "misc": {
        "doom64exsound": "",
        "doomrpg": {
            "brightmaps": "",
            "extras": "",
            "rlarsenalpath": "",
            "rlarsenalwad": "",
            "rlhudwad": "",
            "rlmonsterspath": "",
            "rlmonsterswad": "",
            "vanilla": ""
        },
        "preselectedengine": "gzdoom"
    },
    "modlistpath": "/home/nojus/games/DOOM(original)/mods/",
    "oblige": {
        "binary": "",
        "configs": "",
        "mappath": ""
    },
    "online": {
        "client": ""
    },
    "savepaths": {
        "doom64ex": "",
        "doomretro": "",
        "doomrpg": "",
        "gzdoom": "/home/nojus/games/DOOM(original)/saves/",
        "prboomp": "",
        "zandronum": "",
        "zdoom": ""
    },
    "screenshotpath": "",
    "wadpath": "/home/nojus/games/DOOM(original)/wad/"
}

$which gzdoom
returns /usr/bin/gzdoom

i have configured gzdoom to look for wads and iwads in the afromentioned folders, and gzdoom works when launching via commandline

I am running Arch Linux x86_64.

PS: I'm suspecting that this issue is just me being unable to configure the app properly, a quick start guide would be appreciated.

**Comment by FreaKzero** [comment]
Closing this due to: https://github.com/FreaKzero/ssgl-doom-launcher/blob/v1/README.md
