### ISSUE TITLE
Design WAD View

### ISSUE THREAD

**Issue by FreaKzero** [FreaKzero/ssgl-doom-launcher#46]
## First Step: Design the oldschool SSGL 2 column layout

- 2 Column Layout
- first Column shows available Wads
- second Column shows selected wads and can be sorted for load order
- third column replaces the drawer selection of the old app

- first column should be filterable by name and kind of extension (PK3, ZIP, WAD etc)
- user should be able to save selected extensions (second column)

## Item Design
Column 1:
State for idle items
State for Hovered Items
State for "selected" items

Column 2:
User should be able to Drag&Drop as also sort by arrows in the Item
User should be able to deselect the item also in Column 2

**Comment by FreaKzero** [comment]
First Feel: 
![image](https://user-images.githubusercontent.com/6339036/67906048-a506ae00-fb73-11e9-88ac-1a149cebcee3.png)

**Comment by scar45** [comment]
What a wonderful surprise to see your plans to resurrect the project! I hope you don't mind if I submit some PRs when I might have the time. It's been a while, but I'm still around too, and still use SSGL (tho my fork) almost every day.

One tiny thing I might add now, is that for column 2, it would be great to also have an "X" button to remove the selected WAD. In the original app, I found it a bit cumbersome to have to re-find the WAD in the first column, to then be able to remove it from the second.

Cheers though @FreaKzero :) Hope you've been well, and this is some great news overall!

**Comment by FreaKzero** [comment]
@scar45 long time no see old friend :)

Im doing fine - thank you, learned alot the last years and that i wasnt able to add new features especially i wanted or fix bugs in the old codebase due to users always stinged my back.

The new Stuff i plan will be also alot easier to maintain and add Features on since Webtechnologies progressed so far by now :)

Hope you are doing good, for sure im always glad to get some help and i will consider your request.

**Comment by FreaKzero** [comment]
Update
![image](https://user-images.githubusercontent.com/6339036/67990522-77366d80-fc36-11e9-87aa-e16be815b06d.png)

**Comment by scar45** [comment]
I am doing very well too, thanks. Love the update with the "X" button, and the new interface is reminiscent of the old, which works! New logo is clean and great as well. Looking forward to tinkering when I can, but probably need some guidance on getting the new codebase up and running for development...I'll keep watch.

**Comment by FreaKzero** [comment]
Right now i only design Stuff in there (the "real app" in electron doesnt do anyright right now)
I will write a developer documentation when i hookup electron with the ui (right now you cant even productive build it yet - just development server)

If you want to start the stuff in the browser its actually very easy now:
- checkout the`setup-v2 ` branch and go into the /app folder
- `npm install`
- `npm run dev:webp`
-  Open in Browser:`http://localhost:8080/`

**Comment by scar45** [comment]
Thanks for the quick howto, and completely understand that things may(/will!) change over time. I'm not even sure if I'll get to tinker with dev soon, but it's good to have these preliminary instructions. One thing is for sure, I will definitely be following updates!

**Comment by FreaKzero** [comment]
Redesigned the Item Boxes - current Status with Animations:
https://webm.red/n7Mt

**Comment by FreaKzero** [comment]
Update: 
Redefined Animations, Defined "Flowtext" font, Dropdown Design with Animations
https://webm.red/view/KXRj.webm

**Comment by FreaKzero** [comment]
Current Status:
https://webm.red/6V3C

**Comment by FreaKzero** [comment]
Working Backend with Settings and WAD loading:
https://webm.red/view/NunJ.webm

**Comment by FreaKzero** [comment]
Status Update:
Several Render fixes, Cleaned up Backend Code and "old" Playbutton UI Pattern like the old SSGL
I think i will leave the 3rd Column (when window is bigger) for now untouched and make an own story for that

https://webm.red/view/gGL7.webm

**Comment by FreaKzero** [comment]
iWAD List Style and Playbutton
https://webm.red/bvLH

**Comment by FreaKzero** [comment]
https://webm.red/view/XxfW.webm
Status: 
- Sorting of Loadorder
- Mainloader Screen
- Multiple iwad load fix
- Custom Wallpaper

**Comment by efraletti** [comment]
Hello,

I used your launcher for years now and am really happy that its development is alive.

The only thing I always missed is setting the sourceport for each list, or package, as it seems is called now.

Everytime I go to settings and change the version number in the path for gzdoom as in gzdoom_xyz, and always name the list as, for example, trailblazer_gz_xyz so I can load the savegames and continue playing even if a new gzdoom release is out there and I make a new list like bladeofagony_gz_abc, but this implies going to settings and changing the path do gzdoom_abc.

I'm sure in the new version something more practical is on the oven. As soon as a beta version is out count on me for testing.

Thank you for the great tool and a nice christmas for you and your family.

**Comment by FreaKzero** [comment]
Hi @efraletti 

Actually there will be a lot of changes what sourceports and Packages belong - when im thinking about the systems/designs i will do a own ticket for that - but whats right now in my head i can say the following:

SourcePorts:
- Sourceports will not be Static anymore - the user can define the "functions" of the sourceport (=> like: can the sourceport even load saves ? - when yes whats the command for that and so on) as also multiple versions of any sourceport as he likes

That was one of the big features i wanted to integrate already in the old SSGL but wasnt able anymore due to deprecation/End of Life of Angular 1.5 and broken Build Process.

2. Packages
Packages will be something like "complete configured games" where you define everything you need (WADs, Sourceports, Build Map first with Oblige) and when you want to just "hit start" 

also a Feature i wanted to make back then - since i have a "daily play" list and always generate new maps with it.

I hope this clarifies the future of SSGL :)

Thanks alot for your kind words and have nice Holidays also!

**Comment by FreaKzero** [comment]
News: 

Nothing new to show today but:

- Was searching for a few days now why i have strange flickering in the App with the Fonts - found the Problem finally (https://github.com/styled-components/styled-components/issues/2900)
- App can now be built 
- Cleaned up Styles and Stylevariables in the Project

**Comment by FreaKzero** [comment]
Update:

Did mostly code cleanup and styling:

- File/Directory Search Components
- Real WAD Directory Selection works (Backend / Saving Settings in Home Directory)
- Custom Wallpaper works with Backend
- Redefined Input Style
- Redefined Wad View, more compact and feels more "defined" now

https://webm.red/view/m9CH.webm

**Comment by FreaKzero** [comment]
Update:
- Refactored Form Components added better styling to button and button elements:

Dont worry about the sourceport thing - this will be removed when i start with the sourceport view

https://webm.red/view/Hhqk.webm

**Comment by FreaKzero** [comment]
Update:
Did alot of Coding the last 2 days and cleaned the mess up i prototyped with as also added the old features

- Reindex Button in the WAD View near Filter
- Multi Language Support (Since i know that many of my users are Russian)
- Savedirectories and Screenshotdirectories in Settings

So - settings and the WAD View is finished for now in my opinion and will start now with designing the sourceports view.


https://webm.red/view/mkOF.webm
