### ISSUE TITLE
Design SourcePorts view

### ISSUE THREAD

**Issue by FreaKzero** [FreaKzero/ssgl-doom-launcher#49]

**Comment by FreaKzero** [comment]
First Draft:
![image](https://user-images.githubusercontent.com/6339036/70870909-8af52380-1f99-11ea-83f1-facd38243b9f.png)

**Comment by FreaKzero** [comment]
Update:
First throw of the Sourceports Design is finished - still have to clean it up and add Animations though:

https://webm.red/view/FK93.webm

@scar45
Really have no idea anymore what parameters are available for every sourceport out there - just using Retrodoom and GZDOOM the last years

do you know any more parameters than Savegame, Screenshot and Config params ?
(deh is used automatic by the file extension ... i think every sourceport uses -deh for loading dehacks)

as also - what do you think about the layout ?

**Comment by scar45** [comment]
It's coming along _very_ nicely! The UI is super modern and slick. Only thing I might change is the 'toast' notification for "Settings Saved" should maybe be centered in the viewport, and also have the text centered within the toast itself. A very minor thing, and not essential of course. 

The 'skin_bg' wallpaper background looks great too. 

As for source ports, I really only use GZDOOM as well, and sometimes Chocolate Doom. I don't know of any more parameters, nor can I guess any that would be needed. I suppose a way around this could be to add custom parameter:value options, but that might be overkill. Would be better to leave it as you have it, and await any feedback from someone who finds it's inefficient.

Overall tho, it's not even Alpha and it looks fantastic!

**Comment by FreaKzero** [comment]
If you want that wallpaper i found it there: https://wallpapersafari.com/w/3Z1fep
As described before - the wallpaper will be configureable - per default its a custom one i personally did (copyright and so on) from scratch (=> https://github.com/FreaKzero/ssgl-doom-launcher/blob/master/app/client/assets/ssglwall.png)

yeah i also dont like that the Toasts look like buttons ... was just glad that the logic worked - i will definiately change them :)

Good idea with the feedback maybe efraletti knows anything more.

thanks for feedback releasing is as alpha since Lists/Packages as also Oblige werent supported in Alpha 

Just want to be sure that Styles and stuff are working on all Platforms with the Alpha before i get to the complicated Stuff ^^

**Comment by scar45** [comment]
Oh I missed the point that the wallpaper is configurable. That makes it even better (and your custom one is a great default).

I can surely test on Linux, even if I can't get time to contribute anything else.

As for chatting, it's best to just hit me up on Keybase :)

**Comment by FreaKzero** [comment]
What i itended with the very "transparent" background designs of the elements were that users can use their own wallpapers - you can see that here at about 0:18 

https://webm.red/view/mkOF.webm

even thinking in the future to use themes for "Hell" and "UAC" so to say red/yellow (like now) and blue/cyan in the future (glows, textcolor as also the icons) as you can imagine right now i was oriented very close to the DOOM 2016 UI Experience :)

Yeah i will hit you up with a Alpha Binary if im allowed to

**Comment by scar45** [comment]
I love the idea of the Hell VS UAC themes, as both work well with the glow format. Basing it off the 2016 DOOM UI is surely not a bad idea either!

**Comment by efraletti** [comment]
@FreaKzero I believe a good implementation would be default value:parameters that are known in the moment, starting with GZDoom, maybe Zandronum, Chocolate Doom and others, but all configurable with an alter/add/delete button on the side.

Since whathever value:parameter is going directly to the program call and that is a list being passed, that would work with any sourceport new or old.

I got some nice WADs in the forums these days and can happily test the launcher in Windows.

**Comment by FreaKzero** [comment]
Update:

- Saving/Deleteing/Using of Sourceports are functional - design of the "Play Drawer" is not finished yet
- Name of Sourceport gets extracted when the binary is selected
- Loading of DeHacked files (-deh) supported now, also refactored alot of code in the backend

savedir config and screen is useless for now - since there are no packages yet (which will use them)

https://webm.red/view/YLmI.webm
