### ISSUE TITLE
Some screenshots...

### ISSUE THREAD

**Issue by PROPHESSOR** [FreaKzero/ssgl-doom-launcher#57]
![image](https://user-images.githubusercontent.com/19251320/76112821-a6495b00-5feb-11ea-90bb-713dcf21f574.png)
![image](https://user-images.githubusercontent.com/19251320/76112829-aa757880-5feb-11ea-9e53-20872bf040ef.png)
I specified the wad folder
![image](https://user-images.githubusercontent.com/19251320/76112838-aea19600-5feb-11ea-984f-357217f52bf4.png)
... and freezed

**Comment by FreaKzero** [comment]
This is the V1 of SSGL - the New Version is based on complete different technologies and strategies - as described in the readme:

The Problem you had is that there WAS a difference between IWADS and WAD folders which will be dealt by an index service by now - which resolves iwads by Names

https://github.com/FreaKzero/ssgl-doom-launcher/blob/master/app/electron/utils/mods.js
https://github.com/FreaKzero/ssgl-doom-launcher/blob/master/app/electron/constants.js
