### ISSUE TITLE
Please add support for Doom Retro and prboom-plus

### ISSUE THREAD

**Issue by duganchen** [FreaKzero/ssgl-doom-launcher#7]
Would it be possible to add support for Doom Retro and prboom-plus?

**Comment by FreaKzero** [comment]
Will look into this as soon i have time and internet again - just moved flats because of jobchange.
Thinking now a longer time about a "custom launcher" Option anyways

**Comment by FreaKzero** [comment]
https://github.com/bradharding/doomretro/issues/306
